# Generated by Django 2.2.24 on 2023-12-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    def get_new_or_old_building(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')

        for flat in Flat.objects.all():
            if flat.construction_year < 2015:
                flat.new_building = False
            else:
                flat.new_building = True
            flat.save()

    def new_or_old_building_backward(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            flat.new_building = False
            post.save()

    dependencies = [
        ('property', '0004_auto_20231201_2124'),
    ]

    operations = [
        migrations.RunPython(get_new_or_old_building, new_or_old_building_backward)
    ]
