# Generated by Django 5.0 on 2023-12-05 17:11
import re
from django.db import migrations


class Migration(migrations.Migration):

    def get_phone_correct(tel):
        if tel.startswith('8') or tel.startswith('7'):
            tel = f'+7{tel[1:]}'
        
        clear_phone = re.sub(r'[^a-zA-Z0-9]', '', tel)
        return clear_phone


    def get_phone(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')

        for flat in Flat.objects.all():
            phone = flat.owners_phonenumber
            clear_phone = re.sub(r'[^a-zA-Z0-9]', '', phone)
            if phone.startswith('8') or phone.startswith('7'):
                phone = f'+7{phone[1:]}'
        
            
            flat.owner_pure_phone = phone
            flat.save()

    


    
    
    dependencies = [
        ('property', '0010_alter_flat_like_alter_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(get_phone)
    ]
